version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  deploy:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run deploy

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^main/
