version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  deploy:
    executor:
      name: node/default
      tag: '14.15.3'
    environment:
      USE_SSH: 'true'
      GIT_USER: circleci
    steps:
#      - run: |
#          git config --global user.email "ci@elastiflow.com"
#          git config --global user.name "circleci"
      - add_ssh_keys:
          fingerprints:
            - "76:27:70:69:2a:19:4d:1c:10:6a:10:2f:9f:f5:8b:02"
      - checkout
      - node/install-packages
      - run: npm run build # TODO: Take build cache from npm run build
      - run: npm run deploy

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^main/
