version: 2.1

orbs:
  node: circleci/node@4.1.0

executors:
  node-executor:
    docker:
      - image: 'cimg/node:14.15.3'
    resource_class: small

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  deploy:
    executor: node-executor
    environment:
      USE_SSH: 'true'
      GIT_USER: circleci
    steps:
      - checkout
      - node/install-packages
      - run: |
          git config --global user.email "ci@elastiflow.com"
          git config --global user.name "circleci"
      - add_ssh_keys:
          fingerprints:
            - "76:27:70:69:2a:19:4d:1c:10:6a:10:2f:9f:f5:8b:02"
      - run: npm run build
      - run: npm run deploy

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /^(main|develop)/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^main/
